In [1]:
import numpy as np

In [25]:
arr = np.array([1, 2, 3, 4, 5])
arr_zero = np.zeros(5)

print(arr)
print()
print(arr_zero)

arr_ones = np.ones(7)
print()
print(arr_ones)

arr10 = np.arange(10,0, -1)
print()
print(arr10)

print()
print(arr + 10)
print(arr[2:4])

[1 2 3 4 5]

[0. 0. 0. 0. 0.]

[1. 1. 1. 1. 1. 1. 1.]

[10  9  8  7  6  5  4  3  2  1]

[11 12 13 14 15]
[3 4]


In [14]:
import numpy as np

In [22]:
arr2 = np.linspace(0, 1, 7)
print(arr2)
print()
print(f'min={np.min(arr)}, max={np.max(arr)}, sum={np.sum(arr)}')

[0.         0.16666667 0.33333333 0.5        0.66666667 0.83333333
 1.        ]

min=1, max=5, sum=15


In [28]:
new_arr = arr10.reshape(2, 5)
print(arr10)
print()
print(new_arr)
print()
print(new_arr.reshape(5,2))

[10  9  8  7  6  5  4  3  2  1]

[[10  9  8  7  6]
 [ 5  4  3  2  1]]

[[10  9]
 [ 8  7]
 [ 6  5]
 [ 4  3]
 [ 2  1]]
